<?php $attributeset = $block->getAttributeSet(); ?>
<?php $store_info = $block->getStoreData(); ?>
<?php $export_url = $block->getUrl('*/*/export'); ?>

<form method="post" action="<?php //echo $block->getUrl('*/*/export') ?>" id="export_edit_form" >
<input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>" />
<div id="result"></div><br/>
<div class="entry-edit form-inline">
	<fieldset id="export_form" class="fieldset admin__fieldset">
		<legend class="admin__legend legend">
			<span>Export Products</span>
		</legend><br>
	<div class="messages"></div>
	<div class="admin__field field field-store_id">
	<label for="store_id" class="label admin__field-label"><span>Store View</span>
	</label>
	<div class="admin__field-control control">
	
	<select id="storeids" name="storeids" class="required-entry">
			<?php  foreach($store_info as $value){ if($value['value']==0){ ?>
				<option value="0"><?php echo $value['label']; ?></option>
			<?php } else { ?>
				<optgroup label="<?php echo $value['label']; ?>"></optgroup>
			<?php if(!empty($value['value'])){ foreach ($value['value'] as $option){ ?>
				<option value="<?php echo $option['value']; ?>"><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;".$option['label'];?></option>
			<?php  } } } } ?>
		</select>
		<div id="product_sku-note" class="note admin__field-note">Please Select Store.</div>
	</div>
	</div>
	
	<!-- Store Dropdown -->
	<div class="admin__field field field-export_for  with-note">
		<label for="export_for" class="label admin__field-label">
			<span>Select Fields For: </span>
		</label>
		<div class="admin__field-control control">
			<select onchange="displayField(this.value)" class=" select admin__control-select" title="Select Fields For" name="export_for" id="export_for">
				<option value='*'>All Fields Export</option>
				<option value='image'>Image Related Fields</option>
				<option value='inventory'>Inventory Related Fields</option>
				<option value='price'>Price Related Fields</option>
				<option value='ucrFields'>Up-sells, Cross-sells and Related Products Related Fields</option>
			</select>
			<div id="product_sku-note" class="note displayFieldMsg admin__field-note">Please select value for export fields.</div>
		</div>
	</div>
	<!-- End of Store Dropdown -->
	
	<!-- Attribute Set Dropdown -->
	<div class="admin__field field field-attr_dropdown  with-note">
		<label for="attr_dropdown" class="label admin__field-label">
			<span>Attribute Set Name:</span>
		</label>
		<div class="admin__field-control control">
			<select class=" select admin__control-select" title="Select Fields For" name="attr_dropdown" id="attr_dropdown">
				<option value="*">Any Attribute Set</option>
				<?php foreach ($attributeset as $attributesetval) { ?>
					<option value="<?php echo $attributesetval['value']; ?>"><?php echo $attributesetval['label']; ?></option>
					<?php }?>
			</select>
			<div id="product_sku-note" class="note admin__field-note">Please Select Attribute Set.</div>
		</div>
	</div>
	<!-- End of Attribute Set Dropdown -->
	
	<!-- Type Dropdown -->
	<div class="admin__field field field-export_for  with-note">
		<label for="export_for" class="label admin__field-label">
			<span>Type: </span>
		</label>
		<div class="admin__field-control control">
			<select class=" select admin__control-select" title="Select Fields For" name="type_dropdown" id="type_dropdown">
				<option value='*'>Any Product Types</option>
				<option value='simple'>Simple Products</option>
				<option value='configurable'>Configurable Product</option>
				<option value='grouped'>Grouped Products</option>
				<option value='virtual'>Virtual Products</option>
				<option value='bundle'>Bundle Products</option>
				<option value='downloadable'>Downloadable Products</option>
			</select>
			<div id="product_sku-note" class="note admin__field-note">Please Select Product Type.</div>
		</div>
	</div>
	<!-- End of Type Dropdown -->
	
	<!-- Status Dropdown -->
	<div class="admin__field field field-export_for  with-note">
		<label for="export_for" class="label admin__field-label">
			<span>Status: </span>
		</label>
		<div class="admin__field-control control">
			<select class=" select admin__control-select" title="Select Fields For" name="status_dropdown" id="status_dropdown">
				<option value='*'>Any Product Status</option>
				<option value='1'>Enabled</option>
				<option value='2'>Disabled</option>
			</select>
			<div id="product_sku-note" class="note admin__field-note">Please Select Product Status.</div>
		</div>
	</div>
	<!-- End of Status Dropdown -->
	
	<!-- Visibility Dropdown -->
	<div class="admin__field field field-export_for  with-note">
		<label for="export_for" class="label admin__field-label">
			<span>Visibility: </span>
		</label>
		<div class="admin__field-control control">
			<select class=" select admin__control-select" title="Select Fields For" name="visibility_dropdown" id="visibility_dropdown">
				<option value='*'>Any Visibility</option>
				<option value='1'>Not Visible Individually</option>
				<option value='2'>Catalog</option>
				<option value='3'>Search</option>
				<option value='4'>Catalog, Search</option>
			</select>
			<div id="product_sku-note" class="note admin__field-note">Please Select Product Visibility.</div>
		</div>
	</div>
	<!-- End of Visibility Dropdown -->
	
</fieldset>
</div>
<div id="export_popup">
	<div class="steps-export" style="display:none">
		<ul class="nav-bar">
			<li id="initialization"><a href="#">Initialization</a></li>
			<li id="total_products"><a href="#">Total Products</a></li>
			<li id="exporting"><a href="#">Exporting</a></li>
			<li id="complate"><a href="#">Complate</a></li>
		</ul>
		<div class="clearfix"></div>
	</div>
	<div id="myProgress" style="display:none;"><div id="myBar"><div id="label"></div></div></div>
	<div id="export_popup1"></div>
</div> <!-- This Code for Popup Content. -->
</form>

<script type="text/javascript">
	function runProfile(){
		getTotalProductsCount();	
	};
	
	function getTotalProductsCount(){
		require([
		'jquery',
		'mage/template',
		'jquery/ui',
		'mage/translate',
		'Magento_Ui/js/modal/modal',
	],
	 function(jQuery) {
		 jQuery('#export_popup').modal('openModal');
		 jQuery('.steps-export').show();
		 jQuery('#export_popup1').html('initialization');
		 jQuery('#myProgress').hide();
		 
		jQuery(".action-close").click(function() {
			location.reload(); 
		});
		 
		var response = "";
		var exporturl = "<?php echo $block->getUrl('*/*/exportrecordcount/'); ?>";
		jQuery.ajax({
					url : exporturl,
					data: { 
							'store_id' :document.getElementById("storeids").value,
							'attr_id' : document.getElementById("attr_dropdown").value,
							'type_id' : document.getElementById("type_dropdown").value,
							'export_for' : document.getElementById("export_for").value,
							'status_dropdown' : document.getElementById("status_dropdown").value,
							'visibility_dropdown' : document.getElementById("visibility_dropdown").value,
							form_key: FORM_KEY,
							'categoriesSelect' : jQuery("#categories_categories").val(),
							
							
							
						} ,
					dataType: 'json',
					type: 'post',
					//showLoader:true,
					success: function(data){
						try {
							response = data;
						}catch(e){
							alert("Error: getTotalProductsCount");
						}
						if(response.export_can_proceed==true){
						totalRecords=response.totalOrder;
						jQuery("#total_products").addClass("active");
						jQuery("#export_popup1").html('<img src="<?php echo $block->getViewFileUrl('Magebees_Products::images/loader-1.gif'); ?>" /><br/>'+totalRecords+' Product(s) founds.');
						exportCall(response.splitExport,1,null,response.timestamp);
					} else{					
						var el = document.getElementById('storeids');
						var text = decodeHtml(el.options[el.selectedIndex].innerHTML);
							alert('Selected Store: "'+text.trim()+'" not having Product(s) to export');
							window.location='<?php echo $this->getUrl('*/*/index',array('active_tab'=>'export_tabs'));?>';
						}
					}
				});
		}
	);
}

	var countOfStartedProfiles = 0;
	var countOfUpdated = 0;
	var countOfError = 0;
	var totalRecords = 0;
	var totalPage=0;
	var export_type='*'
	//var checkedList = [];		
	function exportCall(splitRun,page,filename,timestamp){
		var response;
		var exporturl = "<?php echo $block->getUrl('*/*/exportrun/'); ?>";
		require([
			'jquery',
			'jquery/ui',
			'Magento_Ui/js/modal/modal',
		],
		 function(jQuery) {
			  	jQuery.ajax({
					url : exporturl,
					data: { 
							'store_id' : document.getElementById('storeids').value,
							'exportfiletype' : 'csv',
							'splitRun' : splitRun,
							'timestamp' : timestamp,
							'filename' : filename,
							'page' : page,
							'feedfor' : document.getElementById('export_for').value,
							'attr_id' : document.getElementById('attr_dropdown').value,
							'type_id' : document.getElementById("type_dropdown").value,
							'export_for' : document.getElementById("export_for").value,
							'status_dropdown' : document.getElementById("status_dropdown").value,
							'visibility_dropdown' : document.getElementById("visibility_dropdown").value,
							'categoriesSelect' : jQuery("#categories_categories").val(),
							form_key : FORM_KEY,
						} ,
					dataType: 'json',
					type: 'post',
					//showLoader:true,
					success: function(transport) {
						totalPage++;
						try {
							response = transport;
						}catch(e){
							alert("Error: exportCall");
						}
						if(response.proceed_next==true){
							countOfUpdated = countOfUpdated + response.exportedOrders;
							jQuery("#export_popup1").html('Exported '+countOfUpdated+' out of '+totalRecords+' Product(s).');
							jQuery("#total_products").removeClass("active");
							jQuery("#exporting").addClass("active");
							jQuery('#myProgress').show();
							move(getPercent());
							exportCall(splitRun,response.page,response.filename,response.timestamp);
						}else if(response.filename!=''){
							/* Added Line */
							jQuery("#export_popup1").html('Exported '+countOfUpdated+' out of '+totalRecords+' Product(s).');
							jQuery("#total_products").removeClass("active");
							jQuery("#exporting").addClass("active");
							jQuery('#myProgress').show();
							move(getPercent());
							/* Added Line */
							 mergingCSVFiles(response.filename,1,totalPage,response.timestamp);
							}
						}
				});
			}
		);
	}
	
function mergingCSVFiles(filename,processPage,page,timestamp){
		var response;
		var exporturl = "<?php echo $block->getUrl('*/*/mergecsv/'); ?>";
		require([
			'jquery'
		],
		function(jQuery) {
			  	jQuery.ajax({
					url : exporturl,
					data: {
							'filename' : filename,
							'page' : page,
							'processPage' : processPage,
							'timestamp' : timestamp,
							form_key : FORM_KEY,
						} ,
					dataType: 'json',
					type: 'post',
					//showLoader:true,
					success: function(transport){
						try {
							response = transport;
						}catch(e){
							alert("Error: mergingCSVFiles");			
						}
						if(response.proceed_next==true){
							jQuery("#exporting").removeClass("active");
							jQuery("#complate").addClass("active");
							mergingCSVFiles(response.filename,response.processPage,response.page,response.timestamp);
						}else{
							/* Added Line */
							jQuery("#exporting").removeClass("active");
							jQuery("#complate").addClass("active");
							/* Added Line */
							
							jQuery("#myProgress").hide();
							jQuery("#export_popup1").html("Please wait while CSV is being prepared for download... ");
							jQuery("#export_popup1").html('Products Exported Successfully.<br/> <br/>Your file name is <span style="color:#eb5202;"><b>'+response.filename+'</b></span> and located in var/export folder.');
							 window.setTimeout(function(){window.location='<?php echo $this->getUrl('*/*/index',array('active_tab'=>'export_file'));?>';}, 3000);
						}
					}
				});
		}
	);
}
 
 
function decodeHtml(html) {
	var txt = document.createElement("textarea");
	txt.innerHTML = html;
	return txt.value;
}
function getPercent() {
	return Math.ceil((countOfUpdated/totalRecords)*1000)/10;
}
	
	
require([
	'jquery',
	'Magento_Ui/js/modal/modal'
	],
	function($,modal) {
			var options = {
			type: 'popup',
			responsive: true,
			innerScroll: true,
			title: "Export Products",
			buttons: [{
				text: $.mage.__('Close'),
				class: '',
				click: function () {
					this.closeModal();
					window.location="<?php echo $block->getUrl('*/*/index/'); ?>";
				}
			}]
		};
		var popup = modal(options, $('#export_popup'));
	}
);	

function move(width) {
  var elem = document.getElementById("myBar");
  if (width >= 100) {
      clearInterval(id);
    } else {
      elem.style.width = width + '%';
      document.getElementById("label").innerHTML = width * 1  + '%';
    }
}

function displayField(val){
	if(val=="image"){
		jQuery(".displayFieldMsg").html("image, small_image, thumbnail, swatch_image Fields will be include in csv file.");
	}else if(val=="inventory"){
		jQuery(".displayFieldMsg").html("qty, min_qty, use_config_min_qty, is_qty_decimal, backorders, use_config_backorders, min_sale_qty, use_config_min_sale_qty, max_sale_qty, use_config_max_sale_qty, is_in_stock, use_config_notify_stock_qty, manage_stock, use_config_manage_stock, is_decimal_divided Fields will be include in csv file.");
	}else if(val=="price"){
		jQuery(".displayFieldMsg").html("price, special_price Fields will be include in csv file.");
	}else if(val=="ucrFields"){
		jQuery(".displayFieldMsg").html("related_product_sku , related_product_position , crosssell_product_sku , crosssell_product_position , upsell_product_sku , upsell_product_position Fields will be include in csv file.");
	}else{
		jQuery(".displayFieldMsg").html("Please select value for export fields.");
	} 
}
	
</script>