<div id="messages"><div class="messages"><div class="message message-notice notice"><div><?php echo __('<b>TIP :</b> Use this module for update products images after import the products.'); ?></div></div></div></div>
<div class="download_image_info">
<p>This module is used for download products images from live URL and generate CSV according to our extension.</p>
<p>&nbsp;</p>
<p><b>How to Use :-</b></p>
<ul>
	<li>1. Make your CSV file as per given <a href="http://www.magebees.com/media/mconnect_uploadfiles/import-export-products-magento-2-csv/download_images_sample.csv">Sample CSV</a> file.</li>
	<li>2. Upload file from "Download Products Images" section.</li>
	<li>3. Click on "Download Images and Generate csv" button.</li>
	<li>4. Your images are downloaded and store in <b>pub/media/import</b> folder and generate CSV file according to our extension and store in <b>var/import</b> folder.</li>
	<li>5. Now goto <b>MageBees -> Import Export Products -> Import Products -> Run Profile</b>. Select your generated CSV file and click on Validate & Import File Data Button.</li>
</ul>
</div>